services:
  - type: web
    name: tibls-recipe-loader
    env: node
    buildCommand: |
      echo "Using Node version:" && node -v
      echo "Available types:" && ls node_modules/@types || echo "No @types directory found"
      npm run build
    startCommand: npm start
    plan: free
    build:
      packages:
        - imagemagick